name: Playwright-Python-Setup

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    env:
      BASE_URL: https://www.saucedemo.com/

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pipenv'
      - name: Install pipenv
        run: pip install pipenv
      - name: Install python dependencies
        run: pipenv install
      - name: Install playwright dependencies
        run: pipenv run install-playwright-dependencies
      - name: Run e2e-tests-with-reports
        run: pipenv run e2e-tests-with-reports
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Pytest Report            # Name of the check run which will be created
          path: test-report/report.xml    # Path to test results
          reporter: java-junit        # Format of test results